In [25]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
import pandas as pd

In [27]:
data = {'Name': ['Alice','Bob'], 'Age': [25, 30]}

In [28]:
df = pd.DataFrame(data)

In [29]:
df.head() # First 5 rows
 # Summary statistics

    Name  Age
0  Alice   25
1    Bob   30

In [30]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [32]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [33]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [34]:
df[['Name', 'Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [35]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [36]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [37]:
df[df['Age'] > 25] # Rows where Age &gt; 25

  Name  Age
1  Bob   30

In [38]:
df['Gender'] = ['F','M'] # Add new column
df.drop('Age', axis=1,)# Remove column

    Name Gender
0  Alice      F
1    Bob      M

In [39]:
df.isnull()

    Name    Age  Gender
0  False  False   False
1  False  False   False

In [40]:
df.dropna()

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [41]:
df.fillna(0)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [42]:
print(df.columns)

Index(['Name', 'Age', 'Gender'], dtype='str')

In [43]:
df.groupby('Gender') [ 'Age'].mean()

Gender
F    25.0
M    30.0
Name: Age, dtype: float64

In [44]:
df1 = pd.DataFrame({'key': ['A', 'B'], 'Value1': [1, 2]})
df2 = pd.DataFrame({'key': ['A', 'B'], 'Value2': [3, 4]})

In [45]:
pd.merge(df1, df2, on='key')
df1.join(df2, lsuffix='_left', rsuffix='_right')

  key_left  Value1 key_right  Value2
0        A       1         A       3
1        B       2         B       4

In [46]:
#df = pd.read_csv('data.csv')
# df.to_csv('output.csv', index=False)

In [47]:
df.sort_values('Age')
df['Age'].apply(lambda x: x + 1)
df['Name'].unique()
df['Age'].value_counts()

Age
25    1
30    1
Name: count, dtype: int64